CREATE DATABASE dbHospital
GO

USE  dbHospital
GO

CREATE SCHEMA Paciente
GO

CREATE SCHEMA Medico
GO

CREATE SCHEMA Historia
GO 

--Tablas--
CREATE TABLE Paciente.PACIENTE(
	CODPAC INT IDENTITY(1,1) NOT NULL,
	NOMPAC VARCHAR(120),
	APEPATPAC VARCHAR(120) NOT NULL,
	APEMATPAC VARCHAR(120) NOT NULL,
	FECNACPAC DATE NOT NULL,
	SEXPAC CHAR(1) NOT NULL,
	DNIPAC CHAR (8) NOT NULL,
	TELEFPAC VARCHAR (9),
	EMAILPAC VARCHAR(100),
	DOMPAC VARCHAR(120) NOT NULL,
	UBIGEOPAC CHAR(6) NOT NULL,
	FECREGPAC DATETIME,
	OBSERVPAC VARCHAR(250),
	CONSTRAINT PK_CODPAC PRIMARY KEY(CODPAC)
)
GO

CREATE TABLE Historia.HISTORIA(
	CODHIST INT IDENTITY(1,1) NOT NULL,
	FECHIST INT NOT NULL,
	OBSHIST INT NOT NULL,
	CONSTRAINT PK_CODHIST PRIMARY KEY (CODHIST)
)
GO

CREATE TABLE Paciente.HISTORIA_PACIENTE(
	CODHIST INT NOT NULL,
	CODPAC INT NOT NULL,
	CODMEC INT NOT NULL,
	CONSTRAINT PK_CODHIST PRIMARY KEY (CODHIST, CODPAC, CODMEC)
)
GO

CREATE TABLE Historia.TURNO(
	CODTUR INT IDENTITY(1,1) NOT NULL,
	CODPAC INT NOT NULL,
	CODMED INT NOT NULL ,
	CONSTRAINT PK_CODTURNO PRIMARY KEY (CODTUR, CODPAC, CODMED)
)
GO

CREATE TABLE Paciente.TURNO_PACIENTE(
	CODTUR INT NOT NULL,
	CODPAC INT NOT NULL,
	CODMED INT NOT NULL,
	CONSTRAINT PK_CODTUR PRIMARY KEY(CODTUR, CODPAC, CODMED)
)
GO

CREATE TABLE Paciente.UBIGEO(
	CODUBI CHAR(6) NOT NULL,
	DISTUBI VARCHAR(60),
	PROVUBI VARCHAR(60),
	DEPSUB VARCHAR(60),
	CONSTRAINT PK_CODUBI PRIMARY KEY(CODUBI)
)
GO

CREATE TABLE Medico.ESPECIALIDAD(
	CODESP INT IDENTITY(1,1) NOT NULL,
	NOMESP VARCHAR(80) NOT NULL,
	OBSESP VARCHAR(100),
	CONSTRAINT PK_CODESP PRIMARY KEY (CODESP)
)
GO

CREATE TABLE Medico.MEDICO(
	CODMED INT IDENTITY(1,1) NOT NULL,
	NOMMED VARCHAR(120) NOT NULL,
	APEPATMED VARCHAR(120) NOT NULL,
	APEMATMED VARCHAR(120) NOT NULL,
	FECNACMED DATE NOT NULL,
	SEXMED CHAR(1) NOT NULL,
	DNIMED CHAR(8) NOT NULL,
	TELEFMED VARCHAR(9),
	EMAILMED VARCHAR(120),
	DOMMED VARCHAR(120)NOT NULL,
	UBIGEOMED CHAR(6) NOT NULL,
	FECREGMED DATETIME,
	OBSERVMED VARCHAR(180),
	CONSTRAINT PK_CODMED PRIMARY KEY(CODMED)
)
GO

CREATE TABLE Medico.MEDICO_ESPECIALIDAD(
	CODMEDESP INT NOT NULL,
	CODESP INT NOT NULL,
	DESCESP VARCHAR(1000),
	CONSTRAINT PK_CODMEDESP PRIMARY KEY (CODMEDESP)
)
GO
-----RELACIONES---------
ALTER TABLE Paciente.PACIENTE
ADD CONSTRAINT FK_PACIENTE_UBIGEO 
FOREIGN KEY (UBIGEOPAC) REFERENCES PACIENTE.UBIGEO
GO

ALTER TABLE Medico.MEDICO_ESPECIALIDAD
ADD CONSTRAINT FK_MEDICO_ESPECIALIDAD_MEDICO  
FOREIGN KEY (CODESP) REFERENCES Medico.MEDICO 
GO

ALTER TABLE Medico.MEDICO_ESPECIALIDAD 
ADD CONSTRAINT FK_MEDICO_ESPECIALIDAD_ESPECIALIDAD   
FOREIGN KEY (CODESP) REFERENCES Medico.ESPECIALIDAD 
GO

ALTER TABLE Paciente.TURNO_PACIENTE 
ADD CONSTRAINT FK_TURNO_PACIENTE_TURNO    
FOREIGN KEY (CODESP) REFERENCES Historia.TURNO  
GO